### PR TITLE
Split sample SNP evidence files into bins for EFM

### PR DESCRIPTION
**Pull request by rnmitchell**
Previously, an R script was used to split individual sample kintelligence files into 10 bins for use in EFM. Adding this feature into lusSTR.

This PR also fixes a bug when specifying no references for SNP processing.

### CODE REVIEW

**Comment by rnmitchell** [comment]
Not sure why this keeps failing the style check- it's passing on my computer. Otherwise, this is ready for review @standage

**Review by standage — APPROVED** [review]
Looks good to me. If resetting the black version fixes things, I'll be happy to merge this.

**Comment by rnmitchell** [comment]
I am trying! I had version 23.3... I'm working on downgrading but Conda doesn't make it easy...

**Comment by standage** [comment]
Ruh roh, looks like we have a test failure with Python 3.9. It doesn't show details, just a false `file.cmp` result.

**Comment by rnmitchell** [comment]
I'll do some troubleshooting

**Pull request merged**
