### PR TITLE
Make lusSTR a Python package

### LINKED ISSUE #2: Convert to Python package
Want to convert to a python package.

### PR DESCRIPTION
**Pull request by standage**
This update converts lusSTR from a collection of scripts into a unified easily-distributed Python package (closes #2). The changes include the following.

- created a dedicated `lusSTR` directory for the Python package
- created a minimal `__init__.py` file to mark the directory as a Python package
- split the `STR_annotation.py` script into a `cli` module with the main method and argument parsing and an `annot` module with all of the accessory functions; this isn't the One True Way to organize the code: it's a decent start for now, but you may want to organize the code differently or more granularly in the future
- moved the test suite script into the `lusSTR` directory
- added a `setup.py` file with details about the package

Incidentally, I also added a CI configuration so that GitHub will run the test suite each time a PR is created or updated.

### CODE REVIEW

**Comment by standage** [comment]
It should be pretty straightforward to get this integrated into Bioconda, so most users can just install with `conda install -c bioconda lusstr`. Contributors/developers would want to create a dedicated environment on their machine like so.

```
conda create --name lusSTR -y python=3.7 pandas pycodestyle pytest pytest-cov
git clone <url>
cd lusSTR
pip install -e .
```

The last command will read the `entry_points` from the `setup.py` file and create an executable in the environment named `lusSTR`.

```
$ lusSTR -h
usage: lusSTR [-h] [-o FILE] input

positional arguments:
  input                sample(s) in CSV format; first four columns must be
                       Locus, NumReads, Sequence, SampleID

optional arguments:
  -h, --help           show this help message and exit
  -o FILE, --out FILE  file to which output will be written; default is
                       terminal (stdout
```

At the moment, this only replaces the functionality of the `STR_annotation.py` script. We should discuss how to integrate the `format.py` script into the package.

**Comment by standage** [comment]
I spruced up the Makefile and added, among other things, a `make devenv` target to help users set up a development environment.

```
conda create --name lusSTR -y python=3.7 pandas
git clone <url>
cd lusSTR
make devenv
```

**Comment by standage** [comment]
Ready for review and merge!

**Comment by rnmitchell** [comment]
This looks awesome!

**Comment by rnmitchell** [comment]
Do you want me to merge it or do we want to discuss including format.py in it first?

**Comment by standage** [comment]
I'd recommend handling `format.py` in a separate thread. I think this update is a nice self-contained set of changes.

**Pull request merged**
